# Catalog Populator Service is an Independent windows service which will read the data from configured
# external resources like Oracle SQL or MY SQl and creates property terms in E-Workbook catalog based on the configuration specified below

#*************E-Workbook Application server details*************
#Below details are one time configurable. do not update anything.
scheme = https
host = gsk.idbs-eworkbook.com
port = 8443
servicebase = /ewb/services/1.0
acceptXml = application/xml
contentTypeXml = application/xml
acceptJson = application/json
contentTypeJson = application/json
#casertslocation=C:\\Program Files\\Java\\jre1.8.0_231\\lib\\security\\cacerts
casertslocation=/opt/apache-tomcat-9.0.27/webapps/cacerts
#casertslocation=C:\\Program Files (x86)\\Java\\jre1.8.0_121\\lib\\security\\CACERTS

#SSL Security path where Keystore file is stored which is used to establish the secure connection with E-Workbook#
ssl_relative_path = /apps/idbsuser/SSL/biobook.jks
#ssl_password encrypted#

#token generation
clientID=cb22560bb69c12c8


clientSecret=464eb8c67ff35e3b1ded80d5ce6dd9b8

authorization=Y2IyMjU2MGJiNjljMTJjODo0NjRlYjhjNjdmZjM1ZTNiMWRlZDgwZDVjZTZkZDliOA==
redirectUrl=https://gsk.idbs-eworkbook.com:8443
grantType=authorization_code
tokenrequesturl=/ewb/services/1.0/oauth/token
contenttypeform=application/x-www-form-urlencoded


entity_auth=YXBpX3VzZXJwcm9kOkdzMWpidDNwQUU=
authorization=YXBpX3VzZXJwcm9kOkdzMWpidDNwQUU=
url=https://gsk.zifornd.com:8443/Alliance_Env/EWBExportAPI/v1/trigger/AllianceEnv
allianceUrl = https://api.gsk.com/rd/data-restriction/api/v2/agreement-packets



#Catalog Path
emailtuplepath = /Email Notification/Stability/Experiments
alliancePath = /Test/Alliance


entityId=75edd780a8f811ec8d4300000a000014

#GSK API DETAILS
#Consumer details
agreementURL = https://api.gsk.com/rd/data-restriction/api/v2/agreement-packets
accessToken.baseurl=https://federation.gsk.com/as/token.oauth2
consumer.clientId=23ff0250682145deb08253c1ac57dbd2

consumer.clientSecret=Q4srtRjLq4Wbjw9BBPYxqG6d4pRYKDYeJwtWswYq9NeBc91PMJ44tpb5EA9crAZAqPx1
consumer.redirectUrl=https://zifornd.com/
consumer.grantType=client_credentials

allianceAuth =MjNmZjAyNTA2ODIxNDVkZWIwODI1M2MxYWM1N2RiZDI6UTRzcnRSakxxNFdianc5QkJQWXhxRzZkNHBSWUtEWWVKd3RXc3dZcTlOZUJjOTFQTUo0NHRwYjVFQTljckFaQXFQeDE=


cronExperssion = 0 0 5 1/1 * ? *

defaultAdmins = dm541713,vmb61811,ss339177,ssz33936

#MailAPI Details
mailurl=https://api.gsk.com/communication/email/v2

apikey=MjlmNTU2MTMtMGVjNS00NjI2LTgwNjktN2UwNmMzNDQxMzQ0JMH0xq7v03dcu2qrSmqIWYUV7xYRzqge1_3ALNc3RW4e
#From  and To Details
#from=Divya.x.Devanathan@gsk.com

from=DO-Not-Reply@gsk.com
#to=idbs-eworkbook-support@gsk.com
to=vignesh.x.vigneshmanoharan@gsk.com
subject = Alliance User Folder Creation in PROD Environment
#subject = User Modification Happened in Alliance
env = Prod