# Catalog Populator Service is an Independent windows service which will read the data from configured
# external resources like Oracle SQL or MY SQl and creates property terms in E-Workbook catalog based on the configuration specified below

#*************E-Workbook Application server details*************
#Below details are one time configurable. do not update anything.
scheme = https
host = gskdev.idbs-eworkbook.com
#host = gskdevelopment.zifornd.com
port = 8443
servicebase = /ewb/services/1.0
acceptXml = application/xml
contentTypeXml = application/xml
acceptJson = application/json
contentTypeJson = application/json
casertslocation=C:\\Program Files\\Java\\jdk1.8.0_231\\jre\\lib\\security\\cacerts
#casertslocation=/opt/apache-tomcat-9.0.22/webapps/cacerts
#casertslocation=/opt/tomcat/apache-tomcat-9/webapps/cacerts
#casertslocation=C:\\Program Files\\Java\\jdk1.8.0_231\\jre\\lib\\security\\cacerts
#SSL Security path where Keystore file is stored which is used to establish the secure connection with E-Workbook#
ssl_relative_path = ssl/ewb.9.2.server.ssl.keystore
#ssl_password encrypted#
ssl_password = cGFzc3dvcmQ=

#token generation
clientID=6f27ca94d8dca019
clientSecret=cd29d62f2d035dd88cba18b8f4eaf4cf
authorization=NmYyN2NhOTRkOGRjYTAxOTpjZDI5ZDYyZjJkMDM1ZGQ4OGNiYTE4YjhmNGVhZjRjZg==
redirectUrl=https://gskdev.idbs-eworkbook.com:8443/
grantType=authorization_code
tokenrequesturl=/ewb/services/1.0/oauth/token
contenttypeform=application/x-www-form-urlencoded

entity_auth=YWRtaW5hcGkwMTpxSmZbQzZWZUhWdHl5VG5zb2lLSWhjXW11VEVXVEZQcQ==
authorization=YWRtaW5hcGkwMTpxSmZbQzZWZUhWdHl5VG5zb2lLSWhjXW11VEVXVEZQcQ==
url = https://localhost:8081/Alliance_Env/EWBExportAPI/v1/trigger/AllianceEnv

allianceUrl = https://api.gsk.com/rd/data-restriction/api/v2/agreement-packets
entityId=df96b520c2f711ed93b200000a044962
#Catalog Path
emailtuplepath = /Email Notification/Stability/Experiments
alliancePath=/Test/Alliance
#GSK API DETAILS
#Consumer details
agreementURL = https://qa.api.gsk.com/rd/data-restriction/api/v2/agreement-packets
accessToken.baseurl=https://federation-qa.gsk.com/as/token.oauth2
consumer.clientId=TestDRAPI_Dev
consumer.clientSecret=RjtTMBE2nKhoALyvP9sfrPvmgBAh0wU2o8x2NtNSqJbgemMaCxVHA0iyB3g09hA5L5qE
consumer.redirectUrl=https://zifornd.com/
consumer.grantType=client_credentials
allianceAuth = MjNmZjAyNTA2ODIxNDVkZWIwODI1M2MxYWM1N2RiZDI6UTRzcnRSakxxNFdianc5QkJQWXhxRzZkNHBSWUtEWWVKd3RXc3dZcTlOZUJjOTFQTUo0NHRwYjVFQTljckFaQXFQeDE=

#cronExperssion = 0 0/3 * 1/1 * ? *
cronExperssion = 0 0 5 1/1 * ? *

defaultAdmins = dm541713,vmb61811,ss339177,ssz33936

#MailAPI Details
mailurl=https://dev.api.gsk.com/communication/email/v2
apikey=NzU2N2JmOGMtNTMzOS00YjJiLWIxYWYtNTk3YWI2MTU0YmEyAgKHxbwtSPFot_VwSaOrYiDrSQj6GkeEC8t8FIzg17Ie
#From  and To Details
#from=Divya.x.Devanathan@gsk.com
 
from=DO-Not-Reply@gsk.com
#from=kathirvel.x.anandhan@gsk.com
#to=IDBS_COMET_USERS@gsk.com
#to=kathirvel.x.anandhan@gsk.com
to=Ranjithkumar.X.Maruthai@gsk.com,vignesh.x.vigneshmanoharan@gsk.com
#to=idbs-eworkbook-support@gsk.com
subject = Alliance User Folder Creation in DEV Environment
env = Dev 